version: "3.9"
services:
  minio:
    image: quay.io/minio/minio
    hostname: minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - $PWD/minio_data:/data
    networks:
      - minio
      - mlflow
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/mlflow-bucket;
      /usr/bin/mc mb myminio/dvc-demo;
      exit 0;
      "

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - $PWD/psql_data:/var/lib/postgresql/data
    networks:
      - mlflow
    environment:
      POSTGRES_PASSWORD: password

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    hostname: mlflow
    networks:
      - mlflow
    ports:
      - 5000:5000
    volumes:
      - $PWD/mlflow_data:/data
    depends_on:
      - createbuckets
      - postgres
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    command: mlflow server --backend-store-uri postgresql://postgres:password@postgres:5432 --default-artifact-root s3://mlflow-bucket/ --host 0.0.0.0

networks:
  minio:
  mlflow:
