apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
  namespace: seldon-system
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: "admin"
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "password"
  RCLONE_CONFIG_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
